# Generated by Django 5.0.6 on 2024-06-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnrollmentFormSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=55, max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateTimeField()),
                ('year_level', models.CharField(max_length=55)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
